### PR TITLE
Typescript Typings

### LINKED ISSUE #1: Typescript support
Working with Nuxt 2.15.2 with Typescript.

import VueScreenSize from 'vue-screen-size'

end with

`Could not find a declaration file for module 'vue-screen-size'. '…/node_modules/vue-screen-size/dist/vue-screen-size.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-screen-size` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-screen-size';`Vetur(7016)`

### PR DESCRIPTION
**Pull request by LittleBigBug**
Closes #1 
I also did a full rewrite in typescript on [this branch](https://github.com/LittleBigBug/vue-screen-size-ts/tree/develop)

### CODE REVIEW

**Comment by johndatserakis** [comment]
Sorry I lost track of this when you posted it, my bad. I may look into updating this library to Vue 3, and when I do that, I will take a look at that branch you shared and see if I can integrate it. I will update here if I find some time to do it, thank you.

**Comment by johndatserakis** [comment]
I've now updated the package to support Vue 3. Soon, I will attempt to take a look at TS support.

**Comment by Verequies** [comment]
Any update on this? Would be great to use this library instead of re-implementing it.

**Comment by johndatserakis** [comment]
Sorry for the very long wait.

I'm merging this PR as it will at least provide a basic level of typing for the package.

I do not envision TypeScript being fully added to this project. I've had trouble with TypeScript and Vue in the past, and I feel we're probably better just updating the new types file manually. Additionally, I think the branch @LittleBigBug rewrote is a bit too different now, now that I've updated a bunch of stuff for the Vue 3 update. My apologies for not getting that in first and not being able to commit to it.

Sorry again for the wait. I'll get this up and push up a new version.

Edit: released in `v2.1.0`.

**Pull request merged**
